### ISSUE TITLE
Bug: Marking tasks might reshuffle them in the group task list

### ISSUE THREAD

**Issue by SooYap** [AY2425S1-CS2103-F12-2/tp#205]

**Comment by ghos7ie** [comment]
related to #238

**Comment by ghos7ie** [comment]
@dez2003 suggested solution, if you have a better solution pls use that instead.
this is to just save you some time

Change to use LinkedHashSet for the task field in Group object

Update the sort such that it follows the following:
1. Convert the set to a list
2. Sort the list based on parameters
3. insert back into a LHS in order
4. return the new LHS
