### ISSUE TITLE
Enhancement: Commands should be able to recognise when a user has entered an incorrect prefix

### ISSUE THREAD

**Issue by SooYap** [AY2425S1-CS2103-F12-2/tp#222]
For example when adding task to group, if a user enters atg gn/Team 1 tn/task_date sno/A0123456X td/2024-09-09 1900 it won't register as an error

**Comment by ghos7ie** [comment]
Did we do this anywhere else?

We can actually consider this an intended behaviour of our app, i.e. we only check for valid prefixes and ignore the invalid ones

**Comment by SooYap** [comment]
Yeah this feature was present in the edit commands (I think) so I thought it’d be nice if we could extend it to the other commands too
