### ISSUE TITLE
Bug: inconsistent task status in group's task list and in the model's task list

### ISSUE THREAD

**Issue by YANYAN-w** [AY2425S1-CS2103-F12-2/tp#251]
when adding an overdue task to a group, the task in the model's filtered task list still has the pending status instead of overdue.

**Comment by ghos7ie** [comment]
@YANYAN-w can you provide screenshots?

**Comment by YANYAN-w** [comment]
![image](https://github.com/user-attachments/assets/27d5642f-5c78-470a-9279-bf57862f67f7)
where the target task is obtained from :
```ruby
List<Task> lastShownList = model.getFilteredTaskList();
Task target = lastShownList.get(taskIndex.getZeroBased());
```
and task in set is obtained from
```ruby
        for (Task t : group.getTasks()) {
            System.out.println("Task in set: " + t);
        }
```
