### ISSUE TITLE
Bug: Find task command is inconsistent, Find student command should throw an exception in the results display panel

### ISSUE THREAD

**Issue by SooYap** [AY2425S1-CS2103-F12-2/tp#300]
I have several tasks in the task list, 3 of which are:
1) test
2) test overdue to pending
3) testingg

But when I execute the command ft q/test, only the first two show up as search results. Is it better if we tweak the search criteria to make sure that the third one gets included too? 

Also for Find Student, when I execute command fs q/Alex Yeoh, I assume an exception is to be thrown, but it is only reflected in the IDE. Maybe it is better to allow search results of multiple words? Same thing happens for find tasks too.

<img width="685" alt="Screenshot 2024-11-07 at 12 20 04 AM" src="https://github.com/user-attachments/assets/7b4407ee-b58d-4b87-9290-e8cc76b6e1d0">

Overall the find groups function seems to be the simplest and most consistent, so maybe we can tweak the other two such that they are standardised.

@ghos7ie lmk if you need help with this or if you feel the different search implementations can remain as is

**Comment by ghos7ie** [comment]
o yes, I will test out and see if it works first

find student uses a different comparing method, that's why it only allows 1 word

Will update it to match find group
