### ISSUE TITLE
[PE-D][Tester A] Missing Closing Bracket

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-2/tp#347]
![image.png](https://raw.githubusercontent.com/LimErnest/ped/main/files/5860ee74-3ad2-49e5-8357-47ecb94febd4.png)

missing closing "]" bracket for the format at the end, leads to ambiguous understanding of the td/ prefix

suggestion: check for typos in UG thoroughly

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: LimErnest/ped#3

**Comment by ghos7ie** [comment]
Duplicate of #396
