### ISSUE TITLE
[PE-D][Tester A] Repetitive visuals and long scenarios

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-2/tp#394]
Too many screenshots are added throughout the user guide and multiple scenarios were added making it cumbersome and difficult to scroll through

suggestion: reduce the number of scenarios and screenshot in the UG  

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: LimErnest/ped#12

**Comment by ghos7ie** [comment]
Many screenshots due to many features, we feel that it is necessary since the display changes quite a bit for our application
