### ISSUE TITLE
[PE-D][Tester B] find_g does not work as intended

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-2/tp#404]
According to the user guide,

![image.png](https://raw.githubusercontent.com/LiuYJ2002/ped/main/files/5909d20e-5328-4858-baea-7658d68a8807.png)

------------------------------------------------------------------------------------

When the command `find_g q/cs2103-f11-100` is used, it did not work as the results are not searched. (image below). It returns a message `3 group(s) listed!` which is wrong too as only one group matches with the query

![image.png](https://raw.githubusercontent.com/LiuYJ2002/ped/main/files/7e34ce1b-5914-4250-bee6-5c9f11751a6e.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: LiuYJ2002/ped#18

**Comment by ghos7ie** [comment]
![image](https://github.com/user-attachments/assets/9948e947-3df3-432e-9722-d95cf2ae3d2e)

Predicate logic is working as intended, however, UI is not displaying correctly

**Comment by ghos7ie** [comment]
Update the filtered group list is being passed but the panel is not updating

Feature can be removed tbh, most TAs have at most 3 groups with unique namings so it isn't too difficult for them to find their groups
