### ISSUE TITLE
Bug: Edit Global Task List

### ISSUE THREAD

**Issue by SooYap** [AY2425S1-CS2103-F12-2/tp#420]
Steps to recreate:

1) Create 2 new groups: cs2103-a1-1 and cs2103-a1-2
2) Add a new task to both groups 
<img width="1077" alt="Screenshot 2024-11-11 at 2 11 28 PM" src="https://github.com/user-attachments/assets/c86afd3d-bf47-4b68-b266-7aa6ca3e9ffd">
3) Add a new task to only cs2103-a1-1
<img width="1075" alt="Screenshot 2024-11-11 at 2 12 16 PM" src="https://github.com/user-attachments/assets/9637b32f-705b-4efd-93aa-479674178579">
4) Now edit the first task (the one named testtt) so that it has the same task name and task deadline as the second task (test2222)
<img width="1077" alt="Screenshot 2024-11-11 at 2 13 53 PM" src="https://github.com/user-attachments/assets/448c6501-a497-45f3-889e-438328c40e51">
You should see a few problems here. Firstly I think editing tasks such that they have the same details as another task in the task list shouldn't be allowed at all. **Secondly in the results display we should just remove the status of the task because editing it to become something else will invariably cause some problems**. Not sure if this problem listed in bold is fixable or not at this point but it's a small problem anyway so its probably fine.

Here comes the bug:
5) Run delete task on the task. 

<img width="1076" alt="Screenshot 2024-11-11 at 2 16 54 PM" src="https://github.com/user-attachments/assets/de88b17b-e1b5-41a7-b5fc-d363c818256b">

The task does not get deleted. 
The reason why this bug happens is because when you edit the first task to have the same details as the second, the system increases the number of tasks in group by the number of tasks that was in the original group. So you can see the first task initially had 2 groups and the second task initially had 1 group, so the final numTasksInGroup is 3. However this is wrong because 1 of the groups has both tasks and this was not accounted for, which causes the problem later on when the task is deleted globally.

Suggested Fixes:
1) Better handling of numTasksInGroup when editing tasks
2) Change display message of tasks so that they remove the status feature (or do this for some cases only where there are problems in the message)
3) Ideally should just prevent people from editing tasks to have the same details as another task so this whole fiasco can be prevented. But... this is probably not fixable now and it's not technically considered a bug too

**Comment by ghos7ie** [comment]
As discussed

>  **Secondly in the results display we should just remove the status of the task because editing it to become something else will invariably cause some problems**. Not sure if this problem listed in bold is fixable or not at this point but it's a small problem anyway so its probably fine. 

This cannot be fixed I believe

but the overall behaviour can be fixed as mentioned by the course website

> This can be allowed only if the current behavior causes the software to misbehave (i.e., crash, give incorrect results, store inconsistent data, or make it unusable for typical users).

Task that should be deleted is not deleted
